openapi: 3.0.3
info:
  title: Core API
  description: |-
    Core API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Health
  - name: Authentication
  - name: Businesses

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Success 200
          $ref: '#/components/responses/SuccessResponse200'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  /businesses:
    post:
      tags:
        - Businesses
      summary: Create a business profile
      description: Creates the primary business owned by the authenticated admin.
      operationId: createBusiness
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessCreatePayload'
      responses:
        '201':
          description: Business created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessResponse'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '403':
          description: Error 403
          $ref: '#/components/responses/ErrorResponse403'
        '409':
          description: Error 409
          $ref: '#/components/responses/ErrorResponse409'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  /businesses/me:
    get:
      tags:
        - Businesses
      summary: Get the authenticated admin's business
      description: Returns the business linked to the authenticated admin.
      operationId: getMyBusiness
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Business found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessResponse'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '403':
          description: Error 403
          $ref: '#/components/responses/ErrorResponse403'
        '404':
          description: Error 404
          $ref: '#/components/responses/ErrorResponse404'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  /businesses/{businessId}:
    patch:
      tags:
        - Businesses
      summary: Update a business profile
      description: Updates allowed fields for the specified business.
      operationId: updateBusiness
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessUpdatePayload'
      responses:
        '200':
          description: Business updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessResponse'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '403':
          description: Error 403
          $ref: '#/components/responses/ErrorResponse403'
        '404':
          description: Error 404
          $ref: '#/components/responses/ErrorResponse404'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  /businesses/assets:
    post:
      tags:
        - Businesses
      summary: Upload a business asset
      description: Accepts logo or payout images and stores them via Supabase Storage.
      operationId: uploadBusinessAsset
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: File to upload.
                assetType:
                  $ref: '#/components/schemas/BusinessAssetType'
              required:
                - file
                - assetType
      responses:
        '200':
          description: Asset uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAssetUploadResponse'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '403':
          description: Error 403
          $ref: '#/components/responses/ErrorResponse403'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  # Authentication
  /auth/sign-up:
    post:
      tags:
        - Authentication
      summary: Sign up by email and password
      description: Sign by providing their email and password
      operationId: signUpByEmailAndPassword
      requestBody:
        required: true
        description: Signup payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpEmailPasswordPayload'
      responses:
        '200':
          description: Successful signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericSuccess'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UID:
      type: string
      example: "12345abcde"
    Email: # Maybe change this back to email format due to error message
      type: string
      format: email
      # pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      example: "example@starter.com"
    Password:
      type: string
      format: password
      #      pattern: ^[a-zA-Z0-9]*[!@#$%^&*][a-zA-Z0-9!@#$%^&*]{7,19}$
      example: "1234567@"
    User:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UID"
        email:
          $ref: "#/components/schemas/Email"
      required:
        - id
        - email
    SignUpEmailPasswordPayload:
      type: object
      properties:
        email:
          $ref: "#/components/schemas/Email"
        password:
          $ref: "#/components/schemas/Password"
      required:
        - email
        - password
    SignUpEmailPasswordResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UID"
        email:
          $ref: "#/components/schemas/Email"
      required:
        - id
        - email

    GenericSuccess:
      type: object
      description: Generic success response
      properties:
        status:
          type: integer
        message:
          type: string
          example: "Ok"
      required:
        - status
        - message
    GenericError:
      type: object
      description: Generic error response
      properties:
        status:
          type: integer
        error:
          type: string
          example: "INVALID_INPUT"
        message:
          type: string
          example: "Some error"
      required:
        - status
        - error
        - message
    Business:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
        logoUrl:
          type: string
          format: uri
          nullable: true
        contactNumber:
          type: string
        gcashQrUrl:
          type: string
          format: uri
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - contactNumber
        - createdAt
        - updatedAt
    BusinessResponse:
      type: object
      properties:
        business:
          $ref: '#/components/schemas/Business'
      required:
        - business
    BusinessCreatePayload:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        contactNumber:
          type: string
        logoUrl:
          type: string
          format: uri
          nullable: true
        gcashQrUrl:
          type: string
          format: uri
          nullable: true
      required:
        - name
        - contactNumber
    BusinessUpdatePayload:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        contactNumber:
          type: string
        logoUrl:
          type: string
          format: uri
          nullable: true
        gcashQrUrl:
          type: string
          format: uri
          nullable: true
    BusinessAssetType:
      type: string
      enum:
        - logo
        - payout_qr
    BusinessAssetUploadResponse:
      type: object
      properties:
        url:
          type: string
          format: uri
      required:
        - url

  responses:
    SuccessResponse200:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericSuccess'
    ErrorResponse400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse409:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
