openapi: 3.0.3
info:
  title: Core API
  description: |-
    Core API
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: Health
  - name: Authentication
  - name: Transactions

paths:
  /api/v1/health:
    get:
      tags:
        - Health
      summary: Health check
      description: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Success 200
          $ref: '#/components/responses/SuccessResponse200'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  # Authentication
  /api/v1/auth/sign-up:
    post:
      tags:
        - Authentication
      summary: Sign up by email and password
      description: Sign by providing their email and password
      operationId: signUpByEmailAndPassword
      requestBody:
        required: true
        description: Signup payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpEmailPasswordPayload'
      responses:
        '200':
          description: Successful signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericSuccess'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

  # Transactions
  /api/v1/transactions/create:
    post:
      tags:
        - Transactions
      summary: Create transaction
      description: Append a new transaction to the transactions table
      operationId: createTransaction
      requestBody:
        required: true
        description: Transaction payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionPayload'
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Error 400
          $ref: '#/components/responses/ErrorResponse400'
        '401':
          description: Error 401
          $ref: '#/components/responses/ErrorResponse401'
        '500':
          description: Error 500
          $ref: '#/components/responses/ErrorResponse500'

components:
  schemas:
    UID:
      type: string
      example: "12345abcde"
    Email: # Maybe change this back to email format due to error message
      type: string
      format: email
      # pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      example: "example@starter.com"
    Password:
      type: string
      format: password
      #      pattern: ^[a-zA-Z0-9]*[!@#$%^&*][a-zA-Z0-9!@#$%^&*]{7,19}$
      example: "1234567@"
    User:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UID"
        email:
          $ref: "#/components/schemas/Email"
      required:
        - id
        - email
    SignUpEmailPasswordPayload:
      type: object
      properties:
        email:
          $ref: "#/components/schemas/Email"
        password:
          $ref: "#/components/schemas/Password"
      required:
        - email
        - password
    SignUpEmailPasswordResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UID"
        email:
          $ref: "#/components/schemas/Email"
      required:
        - id
        - email

    TransactionType:
      type: string
      enum:
        - expense
        - income
      example: expense
    TransactionAmount:
      type: string
      example: "42.50"
      description: Positive decimal amount with 2 decimal places
      pattern: "^(?:0\\.[0-9]{1,2}|[1-9][0-9]*\\.[0-9]{2})$"
    TransactionBase:
      type: object
      properties:
        user_id:
          $ref: "#/components/schemas/UID"
        occurred_at:
          type: string
          format: date-time
          example: "2024-06-01T13:45:00Z"
        amount:
          $ref: "#/components/schemas/TransactionAmount"
        type:
          $ref: "#/components/schemas/TransactionType"
        expense_category_id:
          type: string
          nullable: true
          example: "personal"
        expense_subcategory_id:
          type: string
          nullable: true
          example: "beauty_care"
        income_category_id:
          type: string
          nullable: true
          example: null
        notes:
          type: string
          nullable: true
          example: "makeup"
        transaction_tag:
          type: string
          nullable: true
          example: "want"
      required:
        - user_id
        - occurred_at
        - amount
        - type

    CreateExpenseTransactionPayload:
      allOf:
        - $ref: "#/components/schemas/TransactionBase"
        - type: object
          properties:
            type:
              type: string
              enum:
                - expense
            expense_category_id:
              type: string
            transaction_tag:
              type: string
          required:
            - type
            - expense_category_id
            - transaction_tag
    CreateIncomeTransactionPayload:
      allOf:
        - $ref: "#/components/schemas/TransactionBase"
        - type: object
          properties:
            type:
              type: string
              enum:
                - income
            income_category_id:
              type: string
          required:
            - type
            - income_category_id
    CreateTransactionPayload:
      oneOf:
        - $ref: "#/components/schemas/CreateExpenseTransactionPayload"
        - $ref: "#/components/schemas/CreateIncomeTransactionPayload"

    Transaction:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UID"
        user_id:
          $ref: "#/components/schemas/UID"
        occurred_at:
          type: string
          format: date-time
          example: "2024-06-01T13:45:00Z"
        created_at:
          type: string
          format: date-time
          example: "2024-06-01T13:45:00Z"
        amount:
          $ref: "#/components/schemas/TransactionAmount"
        type:
          $ref: "#/components/schemas/TransactionType"
        expense_category_id:
          type: string
          nullable: true
          example: "personal"
        expense_subcategory_id:
          type: string
          nullable: true
          example: "beauty_care"
        income_category_id:
          type: string
          nullable: true
          example: null
        notes:
          type: string
          nullable: true
          example: "makeup"
        transaction_tag:
          type: string
          nullable: true
          example: "want"
      required:
        - id
        - user_id
        - occurred_at
        - created_at
        - amount
        - type

    GenericSuccess:
      type: object
      description: Generic success response
      properties:
        status:
          type: integer
        message:
          type: string
          example: "Ok"
      required:
        - status
        - message
    GenericError:
      type: object
      description: Generic error response
      properties:
        status:
          type: integer
        error:
          type: string
          example: "INVALID_INPUT"
        message:
          type: string
          example: "Some error"
      required:
        - status
        - error
        - message

  responses:
    SuccessResponse200:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericSuccess'
    ErrorResponse400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ErrorResponse500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
