# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2025-11-16T18:54:11+00:00

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import AnyUrl, BaseModel, EmailStr, Field, RootModel, SecretStr


class UID(RootModel[str]):
    root: str = Field(..., examples=['12345abcde'])


class Email(RootModel[EmailStr]):
    root: EmailStr = Field(..., examples=['example@starter.com'])


class Password(RootModel[SecretStr]):
    root: SecretStr = Field(..., examples=['1234567@'])


class User(BaseModel):
    id: UID
    email: Email


class SignUpEmailPasswordPayload(BaseModel):
    email: Email
    password: Password


class SignUpEmailPasswordResponse(BaseModel):
    id: UID
    email: Email


class GenericSuccess(BaseModel):
    status: int
    message: str = Field(..., examples=['Ok'])


class GenericError(BaseModel):
    status: int
    error: str = Field(..., examples=['INVALID_INPUT'])
    message: str = Field(..., examples=['Some error'])


class Business(BaseModel):
    id: UID
    name: str
    description: Optional[str] = None
    logoUrl: Optional[AnyUrl] = None
    contactNumber: str
    gcashQrUrl: Optional[AnyUrl] = None
    createdAt: datetime
    updatedAt: datetime


class BusinessResponse(BaseModel):
    business: Business


class BusinessCreatePayload(BaseModel):
    name: str
    description: Optional[str] = None
    contactNumber: str
    logoUrl: Optional[AnyUrl] = None
    gcashQrUrl: Optional[AnyUrl] = None


class BusinessUpdatePayload(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    contactNumber: Optional[str] = None
    logoUrl: Optional[AnyUrl] = None
    gcashQrUrl: Optional[AnyUrl] = None


BusinessAssetType = Literal['logo', 'payout_qr']


class BusinessAssetUploadResponse(BaseModel):
    url: AnyUrl
