# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2026-01-11T23:17:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional, Union
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    RootModel,
    SecretStr,
    conint,
    constr,
)


class UID(RootModel[str]):
    root: str = Field(..., examples=['12345abcde'])


class Email(RootModel[EmailStr]):
    root: EmailStr = Field(..., examples=['example@starter.com'])


class Password(RootModel[SecretStr]):
    root: SecretStr = Field(..., examples=['1234567@'])


class User(BaseModel):
    id: UID
    email: Email


class SignUpEmailPasswordPayload(BaseModel):
    email: Email
    password: Password


class SignUpEmailPasswordResponse(BaseModel):
    id: UID
    email: Email


class TransactionType(Enum):
    expense = 'expense'
    income = 'income'


class TransactionAmount(RootModel[float]):
    root: float = Field(..., description='Positive decimal amount', examples=[42.5])


class TransactionBase(BaseModel):
    user_id: UID
    occurred_at: AwareDatetime = Field(..., examples=['2024-06-01T13:45:00Z'])
    amount: TransactionAmount
    notes: Optional[str] = Field(None, examples=['makeup'])


class TransactionMeta(BaseModel):
    id: UID
    created_at: AwareDatetime = Field(..., examples=['2024-06-01T13:45:00Z'])


class CreateExpenseTransactionPayload(TransactionBase):
    type: Literal['expense'] = Field(..., examples=['expense'])
    transaction_tag: str = Field(..., examples=['want'])
    expense_category_id: str = Field(..., examples=['personal'])
    expense_subcategory_id: Optional[str] = Field(None, examples=['beauty_care'])


class CreateIncomeTransactionPayload(TransactionBase):
    type: Literal['income'] = Field(..., examples=['income'])
    income_category_id: str = Field(..., examples=['salary'])


class CreateTransactionPayload(
    RootModel[Union[CreateExpenseTransactionPayload, CreateIncomeTransactionPayload]]
):
    root: Union[CreateExpenseTransactionPayload, CreateIncomeTransactionPayload] = (
        Field(..., discriminator='type')
    )


class UpdateExpenseTransactionPayload(BaseModel):
    type: Literal['expense'] = Field(..., examples=['expense'])
    occurred_at: Optional[AwareDatetime] = Field(
        None, examples=['2024-06-01T13:45:00Z']
    )
    amount: Optional[TransactionAmount] = None
    notes: Optional[str] = Field(None, examples=['makeup'])
    transaction_tag: Optional[str] = Field(None, examples=['want'])
    expense_category_id: Optional[str] = Field(None, examples=['personal'])
    expense_subcategory_id: Optional[str] = Field(None, examples=['beauty_care'])


class UpdateIncomeTransactionPayload(BaseModel):
    type: Literal['income'] = Field(..., examples=['income'])
    occurred_at: Optional[AwareDatetime] = Field(
        None, examples=['2024-06-01T13:45:00Z']
    )
    amount: Optional[TransactionAmount] = None
    notes: Optional[str] = Field(None, examples=['salary payment'])
    income_category_id: Optional[str] = Field(None, examples=['salary'])


class UpdateTransactionPayload(
    RootModel[Union[UpdateExpenseTransactionPayload, UpdateIncomeTransactionPayload]]
):
    root: Union[UpdateExpenseTransactionPayload, UpdateIncomeTransactionPayload] = (
        Field(..., discriminator='type')
    )


class TransactionExpense(TransactionBase, TransactionMeta):
    type: Literal['expense'] = Field(..., examples=['expense'])
    transaction_tag: str = Field(..., examples=['want'])
    expense_category_id: str = Field(..., examples=['personal'])
    expense_subcategory_id: Optional[str] = Field(None, examples=['beauty_care'])


class TransactionIncome(TransactionBase, TransactionMeta):
    type: Literal['income'] = Field(..., examples=['income'])
    income_category_id: str = Field(..., examples=['salary'])


class Transaction(RootModel[Union[TransactionExpense, TransactionIncome]]):
    root: Union[TransactionExpense, TransactionIncome] = Field(
        ..., discriminator='type'
    )


class RecurringFrequency(Enum):
    weekly = 'weekly'
    biweekly = 'biweekly'
    monthly = 'monthly'


class RecurringTemplateBase(BaseModel):
    amount: TransactionAmount
    notes: Optional[str] = Field(None, examples=['Netflix subscription'])
    frequency: RecurringFrequency
    day_of_week: Optional[conint(ge=0, le=6)] = Field(
        None,
        description='Day of week for weekly/biweekly (0=Monday, 6=Sunday)',
        examples=[0],
    )
    day_of_month: Optional[conint(ge=1, le=31)] = Field(
        None, description='Day of month for monthly recurrence (1-31)', examples=[15]
    )
    start_date: AwareDatetime = Field(..., examples=['2024-06-01T00:00:00Z'])
    end_date: Optional[AwareDatetime] = Field(None, examples=['2025-06-01T00:00:00Z'])
    total_occurrences: Optional[int] = Field(
        None,
        description='Total number of occurrences (alternative to end_date)',
        examples=[12],
    )


class RecurringTemplateMeta(BaseModel):
    id: UID
    user_id: UID
    created_at: AwareDatetime = Field(..., examples=['2024-06-01T13:45:00Z'])
    updated_at: AwareDatetime = Field(..., examples=['2024-06-01T13:45:00Z'])
    is_paused: bool = Field(..., description='Whether template is paused')


class CreateRecurringExpenseTemplatePayload(RecurringTemplateBase):
    type: constr(pattern=r'^expense$') = Field(..., examples=['expense'])
    transaction_tag: str = Field(..., examples=['want'])
    expense_category_id: str = Field(..., examples=['personal'])
    expense_subcategory_id: Optional[str] = Field(None, examples=['beauty_care'])


class CreateRecurringIncomeTemplatePayload(RecurringTemplateBase):
    type: constr(pattern=r'^income$') = Field(..., examples=['income'])
    income_category_id: str = Field(..., examples=['salary'])


class RecurringTemplateExpense(RecurringTemplateBase, RecurringTemplateMeta):
    type: constr(pattern=r'^expense$') = Field(..., examples=['expense'])
    transaction_tag: str = Field(..., examples=['want'])
    expense_category_id: str = Field(..., examples=['personal'])
    expense_subcategory_id: Optional[str] = Field(None, examples=['beauty_care'])


class RecurringTemplateIncome(RecurringTemplateBase, RecurringTemplateMeta):
    type: constr(pattern=r'^income$') = Field(..., examples=['income'])
    income_category_id: str = Field(..., examples=['salary'])


class GenericSuccess(BaseModel):
    status: int
    message: str = Field(..., examples=['Ok'])


class GenericError(BaseModel):
    status: int
    error: str = Field(..., examples=['INVALID_INPUT'])
    message: str = Field(..., examples=['Some error'])


class CreateBudgetPlanPayload(BaseModel):
    savings_goal: Optional[float] = Field(
        None, description='Monthly savings goal', examples=[400.0]
    )
    investment_goal: Optional[float] = Field(
        None, description='Monthly investment goal', examples=[280.0]
    )


class UpdateBudgetPlanPayload(BaseModel):
    savings_goal: Optional[float] = Field(None, description='Monthly savings goal')
    investment_goal: Optional[float] = Field(
        None, description='Monthly investment goal'
    )


class BudgetPlan(CreateBudgetPlanPayload):
    id: UUID = Field(..., examples=['550e8400-e29b-41d4-a716-446655440000'])
    user_id: UUID = Field(..., examples=['550e8400-e29b-41d4-a716-446655440001'])
    expected_income: float = Field(
        ..., description='Calculated from recurring income templates', examples=[3600.0]
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime
