"""change column icon to color (income categories)

Revision ID: 274afe1fa989
Revises: 54e884afa902
Create Date: 2026-01-04 17:53:12.484253

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "274afe1fa989"
down_revision: Union[str, Sequence[str], None] = "54e884afa902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("income_categories", sa.Column("color", sa.Text(), nullable=False))
    op.drop_column("income_categories", "icon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "income_categories",
        sa.Column("icon", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("income_categories", "color")
    # ### end Alembic commands ###
