"""Add experience gamification system

Revision ID: 56c68f1f4c63
Revises: e6058eb8d90b
Create Date: 2026-01-21 19:59:07.676759

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56c68f1f4c63'
down_revision: Union[str, Sequence[str], None] = 'e6058eb8d90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('current_level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('profiles', sa.Column('current_xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('last_login_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('total_xp_earned', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('transactions_today_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('last_transaction_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_transaction_date')
    op.drop_column('profiles', 'transactions_today_count')
    op.drop_column('profiles', 'total_xp_earned')
    op.drop_column('profiles', 'last_login_date')
    op.drop_column('profiles', 'longest_streak')
    op.drop_column('profiles', 'current_streak')
    op.drop_column('profiles', 'current_xp')
    op.drop_column('profiles', 'current_level')
    op.drop_table('xp_events')
    # ### end Alembic commands ###
