"""rename spending to expense

Revision ID: 9ffccc7559b4
Revises: 135cdb973a1c
Create Date: 2026-01-04 17:25:41.380815

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ffccc7559b4"
down_revision: Union[str, Sequence[str], None] = "135cdb973a1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_categories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_subcategories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("category_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("sub_color", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("DROP TABLE spending_subcategories CASCADE")
    op.execute("DROP TABLE spending_categories CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_subcategories",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("label", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sub_color", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sort_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["spending_categories.id"],
            name=op.f("spending_subcategories_category_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("spending_subcategories_pkey")),
    )
    op.create_table(
        "spending_categories",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("label", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("color", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sort_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("spending_categories_pkey")),
    )
    op.execute("DROP TABLE expense_subcategories CASCADE")
    op.execute("DROP TABLE expense_categories CASCADE")
    # ### end Alembic commands ###
