"""add transactions table

Revision ID: c637ba4a0636
Revises: f1c2d3e4f5a6
Create Date: 2026-01-04 18:31:37.271459

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c637ba4a0636"
down_revision: Union[str, Sequence[str], None] = "f1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("expense_category_id", sa.Text(), nullable=True),
        sa.Column("expense_subcategory_id", sa.Text(), nullable=True),
        sa.Column("income_category_id", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("transaction_tag", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(type = 'expense' AND expense_category_id IS NOT NULL AND income_category_id IS NULL AND transaction_tag IS NOT NULL) OR (type = 'income' AND income_category_id IS NOT NULL AND expense_category_id IS NULL)",
            name="transactions_category_check",
        ),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expense_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_subcategory_id"],
            ["expense_subcategories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["income_category_id"],
            ["income_categories.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
